In [1]:
import numpy as np
import sys

## The Basics

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [4]:
#Get dimension
a.ndim

1

In [5]:
b.ndim

2

In [6]:
#Get Shape
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [8]:
a.dtype

dtype('int32')

In [9]:
b.dtype

dtype('float64')

In [10]:
a.itemsize

4

In [11]:
#Get total Size
a.size

3

In [12]:
a.nbytes

12

In [13]:
b.nbytes

48

## Accessing/Changing specific elements, rows, columns, e.t.c 

In [14]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [15]:
a.shape

(2, 7)

In [16]:
#Get a specific element [r, c]
a[1, 5]

13

In [17]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
#Get a specifc column
a[:, 2]

array([ 3, 10])

In [19]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [20]:
a[1, 5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [21]:
a[:,2]

array([ 3, 10])

In [22]:
a[:, 2] = 5

In [23]:
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [24]:
a[:, 2] = [3,10]

In [25]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

### 3 Dimensional Arrays

In [26]:
b = np.array([[[1,2], [3, 4]], [[5,6], [7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [27]:
# Get a specific element (work outside in)
b[:,1,1]

array([4, 8])

In [28]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [29]:
# replace
b[:, 1, :] = [[9,9], [8,8]]

In [30]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [31]:
# All zeros matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones((2, 3),dtype = "int32")

array([[1, 1, 1],
       [1, 1, 1]])

In [34]:
#Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [35]:
# Any other number (full_like)
np.full_like(a, 20)

array([[20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20]])

In [36]:
# Random decimal numbers
np.random.rand(2, 3)

array([[0.19779354, 0.21548794, 0.95108236],
       [0.90909749, 0.80075031, 0.09208243]])

In [37]:
np.random.random_sample(a.shape)

array([[0.30980152, 0.22324278, 0.84389644, 0.05667759, 0.62986898,
        0.45005059, 0.25144   ],
       [0.41457934, 0.70134002, 0.43606612, 0.57907595, 0.80597032,
        0.4168937 , 0.0967171 ]])

In [38]:
np.random.random_sample()

0.5372705026946798

In [39]:
#Random integer values
np.random.randint(1, 10, (2, 3))

array([[9, 2, 7],
       [6, 4, 5]])

In [40]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [85]:
#Repeat an Array 
arr = np.array([[1, 2, 3]])
r = np.repeat(arr, 3, axis = 0)

In [86]:
r

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [87]:
 one = np.ones((5,5))

In [44]:
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
one[1:4,1:4] = 0

In [46]:
one

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
one[2, 2] = 9

In [48]:
one

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
output = np.ones((5,5))
output

z = np.zeros((3,3))
z[1, 1] = 9
z

output[1:4, 1:4] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

##### Be careful when copying arrays

In [50]:
import copy

In [51]:
a = np.array([1, 2, 3])
b = copy.copy(a)
b

array([1, 2, 3])

In [52]:
b[0] = 100

In [53]:
b

array([100,   2,   3])

In [54]:
a

array([1, 2, 3])

### Mathematics

In [55]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [56]:
a + 2

array([3, 4, 5, 6])

In [57]:
a - 2

array([-1,  0,  1,  2])

In [58]:
a*2

array([2, 4, 6, 8])

In [59]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [60]:
b = np.array([1, 0, 1, 0])
a+b

array([2, 2, 4, 4])

In [61]:
#Take the sign of all the values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [62]:
np.sin(b)

array([0.84147098, 0.        , 0.84147098, 0.        ])

In [63]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear Algebra

In [64]:
a = np.full((2, 3), 1)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [65]:
b = np.full((3, 2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [66]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [67]:
mult = np.matmul(a, b)

In [68]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [69]:
det = np.linalg.det(mult)

In [70]:
det

0.0

In [71]:
#https://numpy.org/doc/stable/reference/routines.linalg.html


#### Statistics

In [72]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
np.mean(stats)

3.5

In [74]:
np.min(stats)

1

In [75]:
np.sum(stats)

21

#### Reorganizing Arrays

In [76]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
before.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [77]:
#Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [78]:
#Horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load data from file

In [79]:
#Generate text from file
#file = np.genfromtxt("day5", delimiter= ",")
#file.astype("int32")

#####  Boolean Masking and advanced indexing

In [80]:
#file > 50
#file[file > 50]

In [81]:
#You can index with a list in numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1,2,8]]

array([2, 3, 9])

In [88]:
#np.any(file > 50, axis = 0)
#a[[0,1,2,3],[1,2,3,4]]
#a[[0,4,5],3:]

In [89]:
np.__version__

'1.21.5'

In [90]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/USER/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/USER/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/USER/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/USER/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/USER/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/USER/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/USER/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/USER/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy install:
    baselin

In [91]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [93]:
#Test whether the array contains 0 
data = np.array([0, 1, 2, 3, 4])
np.all(data)

True

In [98]:
#Test whether the array is infinite
a = np.array([1, 2, 3, np.nan, np.inf])
np.isfinite(a)

array([ True,  True,  True, False, False])